### ISSUE TITLE
Error on Ender Launch

### ISSUE THREAD

**Issue by Amarie1137** [EnderWiggin/hafen-client#118]
Upon launch, this is the information given: 

> haven.launcher.ValidationException: Could not validate https://enderwiggin.github.io/hafen/hafen.hl
> 	at haven.launcher.Resource.validate(Resource.java:61)
> 	at haven.launcher.Resource.update(Resource.java:84)
> 	at haven.launcher.Driver.run(Driver.java:53)
> 	at haven.launcher.Driver.main(Driver.java:144)
> 	Suppressed: haven.launcher.ValidationException: file not downloaded over tls connection signed with key:rsa:2FA041AE61200B512AC79637E88FD833E31BC8BC7D56E6417B3D3CC14B486392
> 		at haven.launcher.Validator$TlsKeyValidator.validate(Validator.java:43)
> 		at haven.launcher.Resource.validate(Resource.java:55)
> 		... 3 more
>

**Comment by LautaroMRA02** [comment]
https://www.havenandhearth.com/forum/viewtopic.php?f=49&t=40754&hilit=Ender&start=2260

Did you download the launcher again?

**Comment by Amarie1137** [comment]
I'm actually having difficulties remembering how i downloaded it last time.
I have the base game launcher, but no idea how to re-add ender now that
i've removed it... I'm very bad at file management and codes

**Comment by Fr-Dae** [comment]
- Make a clean folder on /Game/Haven/
- download the last version of Java
- Download launcher  https://enderwiggin.github.io/hafen/launcher-hafen.jar
- make sure it's use by default java
- run it

**Comment by Amarie1137** [comment]
All in working order!
