### ISSUE TITLE
Screen rendering issue 

### ISSUE THREAD

**Issue by Haze360** [EnderWiggin/hafen-client#30]
The actual game renders towards the lower left corner of the game window instead of taking up the whole window and the mouse cursor appears to be offset from where is should be for instance to press on the log in button the visible cursor has to be above and to the right of the log in button.
![Screenshot (1)](https://user-images.githubusercontent.com/18321705/113971244-68c68b00-9806-11eb-9d28-16504af28c31.png)

**Comment by ProgrammerDan** [comment]
if you can, find & run it with java 8. I've experienced the same running it in java 11 and 15.

**Comment by EnderWiggin** [comment]
use new updater - it launches game with parameters that fix this issue
