### ISSUE TITLE
RMB Camera rotation

### ISSUE THREAD

**Issue by lua-rocks** [EnderWiggin/hafen-client#42]
When you rotate camera holding a wheel, you need to change position of your index finger and you cannot press the left button at the same time. I also broke two mouses this way, because wheels are very vulnerable on cheap mouses.

Can you please add option to combine middle and right mouse buttons functionality together, to be able to open context menus and rotate camera at the same time on RMB?

**Comment by EnderWiggin** [comment]
hm... in theory it is possible

**Comment by lua-rocks** [comment]
I would be very grateful and I hope it's not a very difficult task.
