### ISSUE TITLE
Adjust grid transparency?

### ISSUE THREAD

**Issue by geebholder** [EnderWiggin/hafen-client#46]
Do you think it's possible to draw the CTRL + G grid with some transparency?
I like it on, but it's a bit intrusive.

**Comment by mdiazcl** [comment]
What do you mean transparency? You can't barely see them 🤔 

Without grid
![imagen](https://user-images.githubusercontent.com/4249887/131944332-7b55d9c5-c9c1-4ad5-a8e7-f42ac5d47012.png)

With grid
![imagen](https://user-images.githubusercontent.com/4249887/131944358-285f7bb9-0f1f-42cc-861c-e23dc540af72.png)

**Comment by EnderWiggin** [comment]
Looks like you're using high render scale. I need to fix this by making line thicker on higher render scales.
