### ISSUE TITLE
[feature] sound settings improve

### ISSUE THREAD

**Issue by Fr-Dae** [EnderWiggin/hafen-client#78]
would it be possible to differentiate the audio channels, 
and thus be able to adjust the volume of the "tic-tic" notifications, 
which are very VERY loud in game, and depend on the "master volume", i.e. to turn them down you have to turn them ALL down :/.

**Comment by EnderWiggin** [comment]
fixed by making notifications use Interface volume slider

**Comment by Fr-Dae** [comment]
@securitymain any comment ?
