### ISSUE TITLE
[issue] Fast moving stacks into container, doesn't stack

### ISSUE THREAD

**Issue by tombabcode** [EnderWiggin/hafen-client#85]
Shift + Click doesn't merge stacks of the same item from Extra info list, which I need to do by hand and it's quite annoying

![info](https://github.com/EnderWiggin/hafen-client/assets/44554710/018442a5-9381-42c8-b4e7-674acf1af9cd)

**Comment by EnderWiggin** [comment]
that list inventory does not operate in stacks if you enable "unwrap stacks" option - it always works in single items. And loftar in his eternal wisdom decided that we don't need auto merging of stacks if we transfer items manually. There's not much I can do at the moment, unfortunately. You can click on stacked items in main inventory for mass transfer for now.
