### ISSUE TITLE
All app files are downoloaded to $HOME directory on Linux

### ISSUE THREAD

**Issue by Nu-hin** [EnderWiggin/hafen-client#9]
### Steps to reporoduce (Ubuntu 18.04, openjdk-11)

1. Download `updater-hafen.jar` to some folder, e.g. `$HOME/Downloads/hafen`.
2. Set the executable bit on `updater-hafen.jar`.
3. Execute the file by double clicking on it.

### Expected behavior:
 - All files are downloaded under `$HOME/Downloads/hafen`

### Actual behavior:
- Files are downloaded to the current user's home directory.

This is quite annoying, as it pollutes homedir with lots of game jar's and configuration files.

**Comment by EnderWiggin** [comment]
That is strange - it is supposed to download files into working dir. Are you launching it in a way that sets its working dir to $HOME ?

**Comment by Nu-hin** [comment]
I just double-click the jar in Nautilus. But I will try to launch from the console and report back.

Meanwhile, maybe this issue should go to updater repo?

**Comment by EnderWiggin** [comment]
yes, it would be better

**Comment by Nu-hin** [comment]
OK, so it seems that Nautilus indeed sets the working dir to home directory.

People here https://stackoverflow.com/questions/4157358/java-linux-working-directory-is-my-home-folder recommend to use paths relative to the current JAR, rather than to the workdir.

**Comment by Nu-hin** [comment]
It looks only you can transfer the issue.

https://help.github.com/en/articles/transferring-an-issue-to-another-repository
